### ISSUE TITLE
MIModel>topWindowIn:  has undeclared class ENoTopWindow in P7

### ISSUE THREAD

**Issue by macta** [juliendelplanque/WindowsPreviewer#14]
I noticed that Pharo7 reports this method has an undeclared error 

topWindowIn: aWorldMorph
	^ (self windowsIn: aWorldMorph)
			detect: #isTopWindow
			ifNone: [ ENoTopWindow signal ]

**Comment by juliendelplanque** [comment]
I checked just now an apparently this problem is gone.
`ENoTopWindow signal` has been replaced by a `self error:...`.
So I close this issue.

Julien
