### ISSUE TITLE
Mirage is queuing up multiple #delaySemaphore waits (which freezes Pharo 7)

### ISSUE THREAD

**Issue by macta** [juliendelplanque/WindowsPreviewer#20]
I keep getting freezes (as in lockups) in my Pharo7 image - and I just noticed that my process browser has 18 delaySemaphore wait operations... that can't be good can it?

![image](https://user-images.githubusercontent.com/5553623/54793847-65223480-4c3c-11e9-8ec7-fa83dc7bb9aa.png)

**Comment by macta** [comment]
I think #continueToScheduleUpdate and #continueToScheduleUpdate: might need to be atomic otherwise there is a race condition?

**Comment by juliendelplanque** [comment]
Hello,

I just fixed this bug by increasing the priority of threads updating thumbnails from 10 to 20.

It looks like this problem is gone. :-)

See PR #22 

Cheers,

Julien
